### ISSUE TITLE
Example Value for failover_locations variable

### ISSUE THREAD

**Issue by dgray1k** [claranet/terraform-azurerm-cosmos-db#1]
Hi,

Firstly, this repro is very helpful for a terraform newbie such as myself, so thanks for committing it to github.

I'm having a small issue that I think is due to me not passing failover_locations  in the correct format, could you please share an example for this variable please?

Many Thanks

Dan

**Comment by jmapro** [comment]
Hello,

Happy to see this project is useful 😄 

The failover_locations variable is a map which correspond to the geo_location parameter in the documentation : https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cosmosdb_account

The prefix must be the name of the key like the example below:

```
  failover_locations = {
    (module.azure-region.location_short) = {
      location = module.azure-region.location
    }
  }
```

For the West Europe location, module.azure-region.location_short will be `euw`

Hope this will help you

**Comment by dgray1k** [comment]
Thanks for your response, that has given me what I needed
