### ISSUE TITLE
New mongo server version for azurerm

### ISSUE THREAD

**Issue by jjpinto** [claranet/terraform-azurerm-cosmos-db#3]
Terraform should make available MongoDB server version 4.2 for azurerm. Azure has had this version for a while and has lots of benefits from the 4.0 to 4.2 version.

On terraform
[mongo_server_version](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cosmosdb_account#mongo_server_version) - (Optional) The Server Version of a MongoDB account. Possible values are 4.0, 3.6, and 3.2.

**Comment by Shr3ps** [comment]
Hello, 
thanks for your issue.

Can you open a Pull-Request to add this new 4.2 possible version value?
Also do you know which version of the AzureRM provider include this?

Thanks!

**Comment by jjpinto** [comment]
Hi,

I'm not completely sure what needs to be done or the impacts would have when applying 4.2 version.
Not sure - based on the searches I did, nobody has it.

**Comment by Shr3ps** [comment]
Hey,

I just checked, and yes 4.2 is not available ATM in the Terraform provider.
Here is the related issue opened https://github.com/hashicorp/terraform-provider-azurerm/issues/15765

We will have to wait for a new release of the provider.

**Comment by BzSpi** [comment]
Mongo 4.2 is now available in the azurerm provider. You may be able to use it in the module.

Please let us know if you have any issue.

https://github.com/hashicorp/terraform-provider-azurerm/blob/main/CHANGELOG.md#360-may-12-2022

**Comment by BzSpi** [comment]
My bad, we have a validation on the variable. I'll fix this.

**Comment by rossifumax** [comment]
Hello ! 

You should be able to use Mongo 4.2 with the version `v6.1.0` of the module.

Thanks for your issue !

**Comment by jjpinto** [comment]
Thank you!
