### ISSUE TITLE
[FEAT] Enable opt-in option for account discount

### ISSUE THREAD

**Issue by kevin-fitlg** [claranet/terraform-azurerm-cosmos-db#4]
### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hi

Azure Cosmosdb support one free account per subscription;

This is an [opt-in feature](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cosmosdb_account#enable_free_tier) and in order to enable it, we need to set `enable_free_tier = true` inside the module. 

There is no complicated condition about this capability. So, I think we can just simply enable it using a new variable `var.enable_free_tier` with default value set to `false`.

I am happy to add this to the module.

### New or Affected Resource(s)/Data Source(s)

azurerm_cosmosdb_account

### References

https://learn.microsoft.com/en-us/azure/cosmos-db/free-tier#free-tier-with-azure-discount
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cosmosdb_account#enable_free_tier

**Comment by Shr3ps** [comment]
Thanks for this feature suggestion!
Feel free to open a pull-request with your suggestion :)
